// Copyright (c) 2026 DIVISION 7 | MI-7 (@divisionseven)
// SPDX-License-Identifier: MIT

// House gate: isolated single-fork runs own green definition.
// Wall-clock flakes under parallel load read as red; config owns flags, not invocations.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    pool: "forks",
    poolOptions: {
      forks: {
        singleFork: true,
      },
    },
    // Why: starvation guard, not a product bound — a loaded host must not turn
    // scheduling delay into red. Assertion walls inside tests stay untouched.
    testTimeout: 30000,
    // Coverage enforcement: 90% floor on lines, branches, functions, statements.
    // reportOnFailure still writes artifacts on red runs; sub-floor exits non-zero.
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "lcovonly"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.ts", "plugin/*.ts"],
      exclude: [
        "src/version.ts", // generated by scripts/gen-version.js
        "tests/**",
        "scripts/**",
      ],
      // reportOnFailure writes artifacts on red runs; enforcement still exits non-zero.
      reportOnFailure: true,
      thresholds: {
        lines: 90,
        branches: 90,
        functions: 90,
        statements: 90,
      },
    },
  },
});
